# -*- coding: utf-8 -*-
"""Exp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12W_dHB0tl7qKnTe8VazhRW4-0Q8Wv4fx
"""

import os
import time

filename = "evidence.txt"

# Create file
with open(filename, "w") as f:
    f.write("Digital Forensics")

# Wait for 2 seconds
time.sleep(2)

# Modify file
with open(filename, "a") as f:
    f.write("\nMetadata Updated")

print("File Timestamp Details")
print("----------------------")
print("Created :", time.ctime(os.path.getctime(filename)))
print("Modified:", time.ctime(os.path.getmtime(filename)))
print("Accessed:", time.ctime(os.path.getatime(filename)))